### ISSUE TITLE
Doesnt work with latest version of redux-persist 5.x

### ISSUE THREAD

**Issue by minmaxdata** [EQuimper/youtubetuto-learn-redux-persist#1]
I created a working repo from you code with some small changes. I have a repo here of a working example of redux-persist from a youtube lesson from EQuimper. Here is is https://github.com/minmaxdata/redux-persist-example

**Comment by EQuimper** [comment]
Thank you @minmaxdata I really appreciate it :) I will do a new video about this and fix this issue. Thank you for the solution I didn't event play with the new version yet :) I will mention you. Thank you again :)
